### ISSUE TITLE
How to set timeout invoking service

### ISSUE THREAD

**Issue by wqliang** [dapr/java-sdk#399] opened 2020-11-27 09:24 UTC
How to set a timeout per request when invokeService ?
invokeService will return a Mono<T>, Mono.block(Duration.ofMills(3000)) and Mono.timeout(Duration.ofMills(3000)) seems not work as I expected.  The default timeout of DaprHttp is 10s .
How can I invoke different service with different timeout with only one daprClient instance?

**Comment by artursouza** [comment] 2020-12-01 06:40
We don't support timeout setting in the SDK - but that could be added. Now, the SDK invokes Dapr sidecar via GRPC and not HTTP by default. So the change should be in GRPC first but implemented in both.

Now, Dapr sidecar does not support timeout per request, so that would be another feature. Maybe it can be done via metadata.

**Comment by artursouza** [comment] 2021-01-19 01:08
This issue is caused by #434. gRPC API is fixed and the Mono.block(timeout) is working now. There is another PR fixing it for HTTP too.

**Comment by artursouza** [comment] 2021-01-19 01:14
By allowing Mono timeout, it does not seem to be a need for a runtime feature to set timeout. We will close this issue once the PR above is merged.

**Closed** 2021-01-21 23:23 UTC
Labels: P1, area/client, kind/bug, question, triaged/resolved
