### ISSUE TITLE
create the actor and related classes according the documentation as base for the java client sdk

### ISSUE THREAD

**Issue by ji11er** [dapr/java-sdk#12] opened 2019-11-10 21:45 UTC
## What to do?

The actor as a basic principle of the concept needs to be created for the java-sdk. According to documentation and existing implementation in C#.

Class names, methods, types ... should be named similarly to avoid confusion.

Work on a plan and discuss with the maintainer.

**Comment by artursouza** [comment] 2019-12-09 20:49
We are working on this as part of a project now. I will close this as duplicate of Issue #29 as a reference but other issues also overlap.

**Closed by artursouza** 2019-12-09 20:49 UTC
Labels: duplicate

**Comment by ji11er** [comment] 2019-12-10 06:11
Hi Artur, I created a lot of classes already. Will you consider to use some
of them?

Artur Souza <notifications@github.com> schrieb am Mo., 9. Dez. 2019, 21:49:

**Comment by artursouza** [comment] 2019-12-10 07:29
I would like to check what you have. Can you send me the link? We are just getting started so this is the right moment to bring in your code.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ji11er** [comment] 2019-12-10 07:43
Hi Artur,

I will create a branch and create a pull request. I will also create a
Readme to deal with my code. You will have it tonight.

Regds,

Swen

**Comment by amanbha** [comment] 2019-12-10 20:52
I would suggest to use java_sdk_wip branch. This branch can be merged to master branch for release. Folks work in their forks, but they should merge back into  java_sdk_wip branch to collaborate.
