### ISSUE TITLE
Timeout not work in service invoke

### ISSUE THREAD

**Issue by qqeasonchen** [dapr/java-sdk#446] opened 2020-11-28 01:55 UTC
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

> 0.1.x
> 0.2.x
> Output of git describe --dirty

## Expected Behavior

Whatever the timeout is setted, an invoking will expire in 10 secondes, seems not work.

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment] 2021-01-19 01:15
Closing as duplicate of #399.

**Closed by artursouza** 2021-01-19 01:15 UTC
