### ISSUE TITLE
java-sdk

### ISSUE THREAD

**Issue by drishtirai** [dapr/java-sdk#619] opened 2021-09-06 18:10 UTC
## Describe the proposal
Develop and publish a new Maven artifact that allows application developers to easily write integration and end-to-end testing with Dapr. Ideally, supporting both standalone and K8s environments.

**Comment by artursouza** [comment] 2021-09-10 02:20
Duplicate of #549, including copy and pasting the text.

**Closed by artursouza** 2021-09-10 02:20 UTC
