### ISSUE TITLE
Use SpringBoot 3.0 subscribe Unable to listen to publishEvent normally 

### ISSUE THREAD

**Issue by AprilOneDay** [dapr/java-sdk#835] opened 2023-02-15 07:40 UTC
use SpringBoot 2.7.8 normal

---------
dapr-sdk:1.7.1

**Comment by AprilOneDay** [comment] 2023-02-15 07:44
dapr-sdk:1.7.1

**Comment by denis111** [comment] 2023-05-15 10:47
I think it's duplicate of https://github.com/dapr/java-sdk/issues/815

**Closed** 2024-02-14 14:46 UTC
Labels: kind/bug
